### ISSUE TITLE
Question about UT4

### ISSUE THREAD

**Issue by bryanhanson** [eoduniyi/hyperSpec.gsoc2020#1]
In this unit test

```
# UT4
  test_that("renaming spectrum column throws error", {
    expect_error(chk.hy(rename(chondro, spc_newcolname = spc)))
  })
```
is the `chk.hy` necessary, since the `rename` method for `hyperSpec` objects calls `chk.hy` already?  I think what you have here calls `chk.hy` on what amounts to an error condition.

Related: have you built & checked your local version of `hyperSpec` with this function present?

**Comment by eoduniyi** [comment]
You are correct: UT4 does not need to have chk.hy because rename.tidyverse already does that. @cbeleites also mentioned the same thing yesterday. I forgot to move that test when I was pasting into this repository. 

When I originally added the function I could "load_all()" and build the package fine. Although, now I'm getting an error: Error: object ‘flu’ is not exported by 'namespace:hyperSpec', but I don't think that has anything to do with rename.R

**Comment by cbeleites** [comment]
wrt. the "flu" error: I'll try to look into that tomorrow or at the latest Monday. As far as I can see right now, it doesn't have to to with rename.

**Comment by eoduniyi** [comment]
Claudia,

I recloned the master branch of your hyperSpec.tidyverse and then reimplemented rename.hyperSpec. Now, load_all() and building the package seems to be working fine.

**Comment by eoduniyi** [comment]
Hello,

I've updated my solutions and have posted a "walkthrough" of me solving them in the [README.md](https://github.com/eoduniyi/hyperSpec.gsoc2020). I am going to close this issue now.
